include $(APPDIR)/Make.defs

PROGNAME  = embfetch
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MAINSRC   = embfetch_main.c
CSRCS     = sysinfo_rtos_common.c sysinfo_nuttx.c

include $(APPDIR)/Application.mk